#!/bin/sh
# Enforce coding style
STAGED_FILES=`git diff --cached --name-only --diff-filter=ACMR`
source .venv/bin/activate
for file in "$STAGED_FILES"
do
    echo "$file" | grep -e ".py$" > /dev/null
    if [ $? -eq 0 ]; then
        isort "$file"
        black "$file"
        git add "$file"
    fi
done
deactivate
